-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 18:39:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LocalizaDescarte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LocalizaDescarte` ;

-- -----------------------------------------------------
-- Schema LocalizaDescarte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LocalizaDescarte` DEFAULT CHARACTER SET utf8 ;
USE `LocalizaDescarte` ;

-- -----------------------------------------------------
-- Table `LocalizaDescarte`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocalizaDescarte`.`usuario` ;

CREATE TABLE IF NOT EXISTS `LocalizaDescarte`.`usuario` (
  `cpf` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LocalizaDescarte`.`loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocalizaDescarte`.`loja` ;

CREATE TABLE IF NOT EXISTS `LocalizaDescarte`.`loja` (
  `cnpj` INT NOT NULL,
  `email_loja` VARCHAR(45) NOT NULL,
  `telefone_comercial` VARCHAR(45) NOT NULL,
  `nome_da_loja` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LocalizaDescarte`.`endereco_loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocalizaDescarte`.`endereco_loja` ;

CREATE TABLE IF NOT EXISTS `LocalizaDescarte`.`endereco_loja` (
  `cep` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`cep`, `loja_cnpj`),
  CONSTRAINT `fk_endereco_loja_loja1`
    FOREIGN KEY (`loja_cnpj`)
    REFERENCES `LocalizaDescarte`.`loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_loja_loja1_idx` ON `LocalizaDescarte`.`endereco_loja` (`loja_cnpj` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LocalizaDescarte`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocalizaDescarte`.`produtos` ;

CREATE TABLE IF NOT EXISTS `LocalizaDescarte`.`produtos` (
  `id_produtos` INT NOT NULL,
  `categorias` VARCHAR(45) NOT NULL,
  `modelos` VARCHAR(45) NOT NULL,
  `ano_modelo` VARCHAR(45) NOT NULL,
  `valor_modelo` INT NOT NULL,
  `usuario_cpf` INT NOT NULL,
  `loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`usuario_cpf`, `loja_cnpj`),
  CONSTRAINT `fk_produtos_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `LocalizaDescarte`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_loja1`
    FOREIGN KEY (`loja_cnpj`)
    REFERENCES `LocalizaDescarte`.`loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produtos_loja1_idx` ON `LocalizaDescarte`.`produtos` (`loja_cnpj` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LocalizaDescarte`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocalizaDescarte`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `LocalizaDescarte`.`agendamento` (
  `date` VARCHAR(45) NULL,
  `usuario_cpf` INT NOT NULL,
  `loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`usuario_cpf`, `loja_cnpj`),
  CONSTRAINT `fk_agendamento_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `LocalizaDescarte`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_loja1`
    FOREIGN KEY (`loja_cnpj`)
    REFERENCES `LocalizaDescarte`.`loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_agendamento_loja1_idx` ON `LocalizaDescarte`.`agendamento` (`loja_cnpj` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
